apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-vapor-setting
spec:
  forms:
    - group: layout
      label: é¦–é¡µ
      formSchema:
        - $formkit: attachment
          name: home_avatar
          id: home_avatar
          key: home_avatar
          label: é¦–é¡µå±•ç¤ºå¤´åƒ
          value: ""
        - $formkit: code
          language: html
          height: 200px
          name: home_slogan
          id: home_slogan
          key: home_slogan
          label: é¦–é¡µä»‹ç»è¯

        - $formkit: number
          name: featured_focus_num
          id: featured_focus_num
          key: featured_focus_num
          label: æ¨èé˜…è¯»ï½œæ•°é‡
          value: 6
          min: 0
          help: é»˜è®¤ 6 æ¡ã€‚è¾“å…¥ 0 åˆ™å…³é—­è¯¥æ¿å—ã€‚
          validation: required

        - $formkit: text
          name: blogger_keywords
          id: blogger_keywords
          key: blogger_keywords
          label: åšä¸»ä»‹ç»å…³é”®è¯
          value: å¼€å‘è€…,æ”»åŸç‹®,ç»†èŠ‚æ§,å†™åšå®¢
          help: "å¿…é¡»ä½¿ç”¨è‹±æ–‡é€—å·åˆ†éš”ï¼Œæœ€å¤šå››ä¸ªè¯è¯­"

        - $formkit: repeater
          name: home_links
          label: ç¤¾äº¤é“¾æ¥
          value:
            - value: twitter
            - value: youtube
            - value: bilibili
            - value: github
            - value: telegram
            - value: email
          children:
            - $formkit: select
              name: value
              label: ç±»å‹
              options:
                - label: Twitteré“¾æ¥
                  value: twitter
                - label: Youtubeé“¾æ¥
                  value: youtube
                - label: Bilibilié“¾æ¥
                  value: bilibili
                - label: Githubé“¾æ¥
                  value: github
                - label: Telegramé“¾æ¥
                  value: telegram
                - label: é¦–é¡µé‚®ç®±
                  value: email
            - $formkit: text
              name: home_links_url
              label: é“¾æ¥

    - group: style
      label: æ–‡æ¡ˆä¸æ ·å¼
      formSchema:
        - $formkit: select
          name: color_scheme
          label: é»˜è®¤é…è‰²
          value: system
          options:
            - label: è·Ÿéšç³»ç»Ÿ
              value: system
            - label: æ·±è‰²
              value: dark
            - label: æµ…è‰²
              value: light
        - $formkit: text
          name: archive_title
          label: æ–‡ç« å½’æ¡£ä»‹æ ‡é¢˜
          value: æ¬¢è¿å…‰ä¸´æˆ‘çš„åšå®¢
          validation: required
        - $formkit: code
          name: archive_slogan
          label: æ–‡ç« å½’æ¡£ä»‹ç»è¯
          height: 200px
          language: html
          value: '<span style="display: inline-block;vertical-align: top;text-decoration: inherit;text-wrap: balance;">
            ğŸŒ¿
            æ¬¢è¿é—¯å…¥è¿™ç‰‡æ–‡å­—æ£®æ—ï¼è¿™é‡Œæ”¶çº³ç€æ¯ä¸€ç¯‡ç”¨å¿ƒä¹¦å†™çš„æ•…äº‹ã€æ€è€ƒä¸æ„Ÿæ‚Ÿï¼Œåƒæ•£è½çš„æ˜Ÿå…‰ç­‰å¾…è¢«ç‚¹äº®ã€‚æ— è®ºä½ æ˜¯å¯»è§…å…±é¸£çš„åŒé¢‘è€…ï¼Œè¿˜æ˜¯å¶ç„¶é©»è¶³çš„æ—…äººï¼Œéƒ½è¯·éšæ„ç¿»é˜…
            â€”â€” æˆ–è®¸ä¸‹ä¸€ç¯‡ï¼Œå°±è—ç€ä½ æƒ³é‡è§çš„æ¸©åº¦ä¸ç­”æ¡ˆï½
            </span>'
        - $formkit: text
          name: search_description
          label: æœç´¢é¡µé¢æè¿°
          value: æœç´¢æ–¹å¼è¦†ç›–æ ‡é¢˜ã€æ‘˜è¦å’Œå…¨æ–‡ï¼Œå»ºè®®æ‰©å¤§è¯æ„æœç´¢ã€‚
        - $formkit: code
          name: notfound_content
          label: 404é¡µé¢æ–‡æ¡ˆ
          height: 200px
          language: html
          value: '
            <h1 class="!mb-4 text-2xl font-bold">å¾ˆæŠ±æ­‰ï¼Œæ‚¨è®¿é—®çš„é¡µé¢è¿·è·¯å•¦ï½</h1>
            <p class="text-zinc-500 dark:text-zinc-400">
            å®ƒå¯èƒ½å»æ¢ç´¢æ˜Ÿè¾°å¤§æµ·ï¼Œä¹Ÿå¯èƒ½åœ¨ä»£ç ä¸›æ—é‡Œè¿·äº†è·¯ã€‚åˆ«æ‹…å¿ƒï¼Œæˆ‘ä»¬å¸®æ‚¨æ‰¾å›å®¶çš„æ–¹å‘ï¼š
            </p>
            <ul class="!mt-8 list-disc space-y-2 pl-5 text-zinc-600 dark:text-zinc-400">
            <li>
            âœ¨ ç‚¹å‡»
            <a href="/" class="font-bold text-zinc-500 hover:underline">é¦–é¡µ</a>
            ï¼Œå¼€å¯æ–°çš„æ¢ç´¢ä¹‹æ—…
            </li>
            <li>ğŸ§­ ç”¨é¡¶éƒ¨æœç´¢æ æ‰¾æ‰¾ä½ å¿ƒä»ªçš„å†…å®¹</li>
            <li>ğŸ“« è‹¥æœ‰ç‰¹åˆ«æƒ³å¿µçš„é¡µé¢ï¼Œä¸å¦¨ç»™æˆ‘ç•™è¨€ â€œå¬å”¤â€ å®ƒï½</li>
            </ul>
            <p>ç¨ç­‰ç‰‡åˆ»ï¼Œè®©æˆ‘ä»¬ä¸€èµ·é‡æ–°ç‚¹äº®è¿™ä¸ªè§’è½å§ ğŸŒŸ</p>'
        - $formkit: code
          name: error_content
          label: 5xxé¡µé¢æ–‡æ¡ˆ
          height: 200px
          language: html
          value: '<h1 class="!mb-4 text-2xl font-bold">å“å‘€ï¼Œçœ‹æ¥æœåŠ¡å™¨æ­¤åˆ»æœ‰ç‚¹å°è¿·ç³Šï½</h1>
            <p class="text-zinc-500 dark:text-zinc-400">
            æ‚¨è®¿é—®çš„é¡µé¢æš‚æ—¶æ— æ³•é¡ºåˆ©åŠ è½½ï¼Œè¿™å¯èƒ½æ˜¯æˆ‘ä»¬æ­£åœ¨è¿›è¡Œåå°ç»´æŠ¤ï¼Œæˆ–æ˜¯çªå¦‚å…¶æ¥çš„æµé‡å°é«˜å³°å¯¼è‡´çš„å°æ’æ›²ã€‚
            </p>
            <p class="font-semibold">åˆ«æ‹…å¿ƒï¼ŒæŠ€æœ¯å°å“¥å·²ç»æ”¶åˆ°ä¿¡å·ï¼Œæ­£åœ¨å¿«é©¬åŠ é­å¤„ç†å•¦ï¼</p>
            <p>æ‚¨å¯ä»¥å°è¯•ï¼š</p>
            <ul class="!mt-8 list-disc space-y-2 pl-5 text-zinc-600 dark:text-zinc-400">
            <li>ğŸŒ± åˆ·æ–°é¡µé¢å†è¯•ä¸€æ¬¡</li>
            <li>ğŸ§­ ç¨åå‡ åˆ†é’Ÿé‡æ–°è®¿é—®</li>
            <li>ğŸ“« è‹¥é—®é¢˜æŒç»­ï¼Œæ¬¢è¿ç•™è¨€å‘Šè¯‰æˆ‘ä»¬å…·ä½“æƒ…å†µ</li>
            </ul>
            <p>æ„Ÿè°¢æ‚¨çš„è€å¿ƒç­‰å¾…ï¼Œæˆ‘ä»¬ä¼šå°½å¿«è®©ä¸€åˆ‡æ¢å¤æ­£å¸¸ï½ ğŸŒŸ</p>'

    - group: links
      label: å‹é“¾é¡µ
      formSchema:
        - $formkit: text
          name: title
          label: æ ‡é¢˜
          value: å‹é“¾
          validation: required
        - $formkit: text
          name: description
          label: æè¿°
          value: æˆ‘éå¸¸å¹¶ä¸”è¿«åˆ‡åœ°å¸Œæœ›èƒ½åœ¨æ‚¨çƒ­æƒ…åœ°æäº¤ä¹‹å‰ï¼Œçœ‹åˆ°æˆ‘ä»¬çš„äº¤æµäº’åŠ¨ï¼Œç”Ÿæ´»åšå®¢æ¯”è¾ƒçœ‹é‡ä»ªå¼æ„Ÿï¼Œæ‰€ä»¥ä¸å¦¨è®©æˆ‘ä»¬äº’ç›¸äº†è§£ä½¿å¾—è¿æ¥æ›´ç´§å®å§ã€‚
        - $formkit: code
          name: content
          label: å†…å®¹
          height: 200px
          language: html
          value: '<p style="font-weight: 400;">å¾ˆé«˜å…´èƒ½å’Œéå¸¸å¤šçš„æœ‹å‹ä»¬äº¤æµï¼Œå¦‚æœä½ ä¹Ÿæƒ³åŠ å…¥å‹é“¾ï¼Œå¯ä»¥ç‚¹å‡»ä¸‹æ–¹æ·»åŠ æŒ‰é’®è¿›è¡Œç”³è¯·ã€‚<mark>ï¼ˆæœ¬ç«™å·²å¼€å¯å‹é“¾æäº¤è‡ªåŠ¨å®¡æ ¸ï¼Œæ‚¨çš„é“¾æ¥å°†ä¼šç¬¬ä¸€æ—¶é—´è¢«æ·»åŠ ã€‚ï¼‰</mark></p><div style="height:1rem" aria-hidden="true" class="wp-block-spacer"></div><ul class="wp-block-list thyuu-block"><li>1. äº¤æµäº’åŠ¨å¹¶ä¸”ä¿æŒè”ç³»ï¼ˆé‡ç‚¹ï¼‰ï¼›</li><li>2. è‡³å°‘æœ‰ 10 ç¯‡åŸåˆ›æ–‡ç« ï¼›</li><li>3. è¯·æå‰åšå¥½æœ¬ç«™é“¾æ¥ã€‚</li></ul>'
        - $formkit: text
          name: admin_email
          label: é‚®ç®±
          validation: required
        - $formkit: checkbox
          name: "enable_comment"
          label: "å…è®¸è¯„è®º"
          value: "true"
          on-value: "true"
          off-value: "false"

    - group: footer
      label: é¡µè„š
      formSchema:
        - $formkit: repeater
          name: sfooter_info
          label: åº•éƒ¨ä¿¡æ¯
          value:
            - sf_title: é„‚ICPå¤‡xxxxxxxå·
              sf_link: https://beian.miit.gov.cn/
              sf_img: /themes/halo-theme-vapor/assets/imgs/icpb.webp
          children:
            - $formkit: text
              name: sf_title
              label: ä¿¡æ¯æ–‡æœ¬
            - $formkit: text
              name: sf_link
              label: ä¿¡æ¯é“¾æ¥
            - $formkit: attachment
              name: sf_img
              label: å›¾æ ‡
              accepts:
                - "image/*"
        - $formkit: checkbox
          name: show_stats
          key: show_stats
          id: show_stats
          label: æ˜¾ç¤ºç»Ÿè®¡ä¿¡æ¯
          value: true
          help: åœ¨ç«™ç‚¹åº•éƒ¨æ˜¾ç¤ºå…¨ç«™çš„ç»Ÿè®¡ä¿¡æ¯

    - group: custom
      label: æ‰©å±•è®¾ç½®
      formSchema:
        - $formkit: textarea
          name: keywords
          label: SEOå…³é”®è¯
          rows: 3
        - $formkit: code
          name: code_css
          label: è‡ªå®šä¹‰CSSä»£ç 
          height: 200px
          language: css
        - $formkit: code
          name: code_js
          label: è‡ªå®šä¹‰JavaScriptä»£ç 
          height: 200px
          language: javascript
        - $formkit: code
          name: head_html
          label: è‡ªå®šä¹‰HTMLä»£ç -å¤´éƒ¨
          height: 200px
          language: html
        - $formkit: code
          name: footer_html
          label: è‡ªå®šä¹‰HTMLä»£ç -åº•éƒ¨
          height: 200px
          language: html

    - group: pluginPage
      label: ç‰¹æ®Šé¡µé¢è®¾ç½®
      formSchema:
        - $formkit: text
          name: douban_description
          label: è±†ç“£é¡µé¢æè¿°
          value: å…‰å½±ã€æ—‹å¾‹ã€æ–‡å­—ã€åƒç´ ä¸èˆå°åœ¨æ­¤äº¤æ±‡ï¼Œæ¯æ®µè®°å½•éƒ½è—ç€å½“æ—¶çš„å¿ƒè·³ä¸æ„Ÿæ‚Ÿã€‚
        - $formkit: checkbox
          name: "douban_comment"
          label: "è±†ç“£é¡µé¢å…è®¸è¯„è®º"
          value: "true"
          on-value: "true"
          off-value: "false"
        - $formkit: text
          name: moments_description
          label: ç¬é—´é¡µé¢æè¿°
          value: ç”Ÿæ´»ç¢ç‰‡åœ¨æ­¤åœæ³Šï¼Œä¸€å¥ç¢å¿µã€åŠå¸§é£æ™¯ã€å¶ç„¶å¿ƒç»ªéƒ½è¢«å¦¥å¸–æ”¶è—ï¼Œæ‹¼å‡‘æˆæ—¶å…‰çš„é²œæ´»æ³¨è„šã€‚
        - $formkit: checkbox
          name: "moments_comment"
          label: "ç¬é—´é¡µé¢å…è®¸è¯„è®º"
          value: "true"
          on-value: "true"
          off-value: "false"
        - $formkit: text
          name: equipment_description
          label: è£…å¤‡é¡µé¢æè¿°
          value: å®ç‰©è£…å¤‡æ¨èï¼Œä¸€èµ·äº«å—ç§‘æŠ€å¸¦æ¥çš„ä¹è¶£
        - $formkit: checkbox
          name: "equipment_comment"
          label: "è£…å¤‡é¡µé¢å…è®¸è¯„è®º"
          value: "true"
          on-value: "true"
          off-value: "false"
        - $formkit: text
          name: photos_description
          label: å›¾åº“é¡µé¢æè¿°
          value: å¸§å¸§å…‰å½±å‡ä½æ—¶å…‰çµ®è¯­ï¼Œæ¯å¹…ç”»é¢éƒ½æ˜¯ç¬”å°–æœªåŠçš„æ¸©æŸ”å¿ƒäº‹ä¸çµæ„Ÿå›å“ã€‚
        - $formkit: checkbox
          name: "photos_comment"
          label: "å›¾åº“é¡µé¢å…è®¸è¯„è®º"
          value: "true"
          on-value: "true"
          off-value: "false"
